### ISSUE TITLE
Lucee was not able to load a Agent dynamically!

### ISSUE THREAD

**Issue by jamiejackson** [Ortus-Solutions/docker-commandbox#15]
I'm starting to run my full app in a commandbox container, but I'm getting the following on app init when it gets to some code that uses JavaLoader.

```
"ERROR","XNIO-2 task-10","10/30/2017","14:41:20","","lucee.runtime.exp.ApplicationException: Lucee was not able to load a Agent dynamically! You need to load one manually by adding the following to your JVM arguments [-javaagent:""/root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar""]
	at lucee.runtime.instrumentation.InstrumentationFactory.getInstrumentation(InstrumentationFactory.java:130)
	at lucee.commons.lang.PhysicalClassLoader.loadClass(PhysicalClassLoader.java:167)
	at lucee.runtime.MappingImpl.getPhysicalClass(MappingImpl.java:249)
	at lucee.runtime.PageSourceImpl._compile(PageSourceImpl.java:368)
	at lucee.runtime.PageSourceImpl.compile(PageSourceImpl.java:333)
	at lucee.runtime.PageSourceImpl.loadPhysical(PageSourceImpl.java:274)
	at lucee.runtime.PageSourceImpl.loadPageThrowTemplateException(PageSourceImpl.java:183)
	at lucee.runtime.PageSourceImpl.loadPage(PageSourceImpl.java:899)
	at lucee.runtime.component.ComponentLoader._search(ComponentLoader.java:281)
	at lucee.runtime.component.ComponentLoader._search(ComponentLoader.java:100)
	at lucee.runtime.component.ComponentLoader.searchComponent(ComponentLoader.java:74)
	at lucee.runtime.PageContextImpl.loadComponent(PageContextImpl.java:3141)
	at lucee.runtime.functions.other.CreateObject.doComponent(CreateObject.java:145)
	at lucee.runtime.functions.other._CreateComponent.call(_CreateComponent.java:42)
	at application_cfc$cf.udfCall3(/search/Application.cfc:365)
	at application_cfc$cf.udfCall(/search/Application.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:227)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698)
	at application_cfc$cf.udfCall1(/search/Application.cfc:112)
	at application_cfc$cf.udfCall(/search/Application.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:227)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698)
	at lib.org.framework.one_cfc$cf.udfCalla(/deployment_root/lib/org/framework/one.cfc:1921)
	at lib.org.framework.one_cfc$cf.udfCall(/deployment_root/lib/org/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:227)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:588)
	at lucee.runtime.SuperComponent.call(SuperComponent.java:82)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698)
	at application_cfc$cf.udfCall1(/search/Application.cfc:91)
	at application_cfc$cf.udfCall(/search/Application.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:227)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1698)
	at search.includes.eventhandler_cfc$cf.udfCall(/plugins/search/includes/eventHandler.cfc:21)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:213)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1931)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1586)
	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:213)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1935)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:835)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1719)
	at config.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/config/appcfc/onApplicationStart_include.cfm:426)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:939)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:833)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:817)
	at config.appcfc.onapplicationstart_method_cfm$cf.udfCall(/config/appcfc/onApplicationStart_method.cfm:51)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:108)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:367)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:227)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
	at lucee.runtime.listener.ModernAppListener.onApplicationStart(ModernAppListener.java:299)
	at lucee.runtime.PageContextImpl.initApplicationContext(PageContextImpl.java:3041)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:119)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2405)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2395)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2363)
	at lucee.runtime.engine.Request.exe(Request.java:46)
	at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1048)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:996)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"
```

I saw [LDEV-1138](https://luceeserver.atlassian.net/browse/LDEV-1138?focusedCommentId=36911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36911), but I'm not sure how to use the workaround in Docker. I tried the following, but it didn't help.

```Dockerfile
FROM ortussolutions/commandbox:latest

#Hard Code our engine environment
ENV CFENGINE lucee@5.2.3+35

# WARM UP THE SERVER
RUN ${BUILD_DIR}/util/warmup-server.sh

ENV LUCEE_VERSION=5
ENV LUCEE_SERVER /root/serverHome/WEB-INF/lucee-server
ENV LUCEE_SERVER_CONTEXT ${LUCEE_SERVER}/context
ENV LUCEE_SERVER_DEPLOY ${LUCEE_SERVER}/deploy
ENV LUCEE_WEB /root/serverHome/WEB-INF/lucee-web
ENV LUCEE_WEB_CONTEXT ${LUCEE_WEB}/context
ENV LUCEE_LIB_DIR /root/serverHome/WEB-INF/lucee-server/bundles

# Here was my ineffective attempt:
ENV JAVA_OPTS=-javaagent:"${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar"

...
```

**Comment by jamiejackson** [comment]
It turns out that the agent isn't bundled with Lucee, so Brad suggested placing a copy.

```
COPY ./conf/lucee-external-agent.jar ${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar
ENV JAVA_OPTS=-javaagent:"${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar"
```

Still no luck, though I'm still not sure that the `JAVA_OPTS` environment variable is respected by the image.

**Comment by bdw429s** [comment]
@jamiejackson Unless @jclausen has done something special to look for an env variable called `JAVA_OPTS`, I think that might be a Tomcat thing.  To add JVM args to a CommandBox-based server, use the `jvm.args` property in your `server.json`.
```
{
  "jvm" : {
    "args" : "-javaagent:\"${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar\""
  }
}
```
I'm not 100% sure on that `${LUCEE_SERVER_CONTEXT}` bit so do a `--debug` start and look at the JVM args in the console out to ensure the right stuff is getting passed to the server.  You'll see two sets of JVM args in the logs.  The first set is the Runwar process that kicks off and the JVM args will all be shoved in one "placeholder" arg.  The second set will be the actual server kicking off and that's the one that counts.

**Comment by jamiejackson** [comment]
Thanks, @bdw429s. Here's the debugging.

`server.json`:
```yml
{
    "web":{
        "rewrites":{
            "enable":"true"
        },
        "http":{
            "port":"8888"
        },
        "ssl":{
            "port":"8443"
        },
        "host":"0.0.0.0"
    },
    "openbrowser":"false",
    "jvm":{
        "args":"-javaagent:\"${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar\""
    },
    "debug":"true",
    "app":{
        "serverHomeDirectory":"/root/serverHome",
        "cfengine":"lucee@5.1"
    }
}
```
Logs:
```log
$ docker logs lucee --follow
INFO: Server Home Directory defined in server.json as: /root/serverHome
INFO: CF Engine defined as lucee@5.1
INFO: Server Home Directory set to: /root/serverHome
INFO: CF Engine set to lucee@5.1
INFO: Engine vendor: lucee
INFO: Engine version: 5
INFO: Lucee web home set to: /root/serverHome/WEB-INF/lucee-web
INFO: Lucee server home set to: /root/serverHome/WEB-INF/lucee-server
INFO: Engine configuration file detected at /tmp/cfConfig.json
Set app.cfengine = lucee@5.1
Set web.http.port = 8888
Set web.ssl.port = 8443
Set web.host = 0.0.0.0
Set app.serverHomeDirectory = /root/serverHome
Set openbrowser = false


start server in - /app/wwwroot/
server name - wwwroot
server config file - /app/wwwroot//server.json
Contacting ForgeBox to determine the latest & greatest version of [lucee 5.1]...  Use an exact 'cfengine' version to skip this check.
OK, [lucee 5.1.4+19] it is!
WAR/zip archive already installed.
Found CFConfigFile environment variable.
CFConfig file set to [/tmp/cfConfig.json].
Importing CFConfig into server [wwwroot]
Config transfered!

Server start command: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    -jar /root/.CommandBox/lib/runwar-3.6.1-SNAPSHOT.jar
    --background=true
    --port 8888
    --host 0.0.0.0
    --stop-port 55020
    --processname wwwroot [lucee 5.1.4+19]
    --log-dir /root/serverHome//logs
    --open-browser false
    --open-url http://0.0.0.0:8888
    --server-name wwwroot
    --tray-icon /root/.CommandBox/cfml/system/config/server-icons/trayicon-lucee.png
    --tray-config /root/.CommandBox/server/BE9DA625CCEEFE0670CFF62B044E8E40-wwwroot/trayOptions.json
    --tray-enable true
    --directoryindex true
    --timeout 240
    --proxy-peeraddress true
    --debug true
    --servlet-rest-mappings ___DISABLED___
    --cfengine-name lucee
    --jvm-args=-javaagent:"/root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar";-Xmx512m
    -war /app/wwwroot/
    --web-xml-path /root/serverHome//WEB-INF/web.xml
    --urlrewrite-enable true
    --urlrewrite-file /root/.CommandBox/cfml/system/config/urlrewrite.xml
The server for /app/wwwroot/ is starting on 0.0.0.0:8888...
2017-11-01 15:23:54 DEBUG RunwarLogger RunwarLogger JDK loggers detected, org.jboss.logging set to level DEBUG
2017-11-01 15:23:54 DEBUG RunwarLogger RunwarLogger JDK loggers detected, RunwarLogger set to level DEBUG
2017-11-01 15:23:54 DEBUG RunwarLogger RunwarLoggerNo log4j loggers detected
2017-11-01 15:23:54 DEBUG RunwarLogger Checking that we're running on > java7
2017-11-01 15:23:54 INFO RunwarLogger Starting background wwwroot [lucee 5.1.4+19] from: /root/.CommandBox/lib/runwar-3.6.1-SNAPSHOT.jar
2017-11-01 15:23:55 DEBUG RunwarLogger launching background process with these args:
2017-11-01 15:23:55 DEBUG RunwarLogger
    /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    -javaagent:"/root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar"
    -Xmx512m
    -jar  /root/.CommandBox/lib/runwar-3.6.1-SNAPSHOT.jar  8888
    --host  0.0.0.0  55020
    --processname  wwwroot [lucee 5.1.4+19]
    --log-dir  /root/serverHome//logs
    --open-browser  false
    --open-url  http://0.0.0.0:8888
    --server-name  wwwroot
    --tray-icon  /root/.CommandBox/cfml/system/config/server-icons/trayicon-lucee.png
    --tray-config  /root/.CommandBox/server/BE9DA625CCEEFE0670CFF62B044E8E40-wwwroot/trayOptions.json
    --tray-enable  true
    --directoryindex  true
    --timeout  240
    --proxy-peeraddress  true
    --debug  true
    --servlet-rest-mappings  ___DISABLED___
    --cfengine-name  lucee
    -war  /app/wwwroot/
    --web-xml-path  /root/serverHome//WEB-INF/web.xml
    --urlrewrite-enable  true
    --urlrewrite-file  /root/.CommandBox/cfml/system/config/urlrewrite.xml
    --background  false
    --port  8888
    --stop-port  55020
2017-11-01 15:23:55 DEBUG RunwarLogger timeout of 240 seconds
Starting in background -
2017-11-01 15:23:55 DEBUG RunwarLogger Error opening zip file or JAR manifest missing : "/root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar"
Error opening zip file or JAR manifest missing : "/root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar"
2017-11-01 15:23:55 DEBUG RunwarLogger Error occurred during initialization of VM
Error occurred during initialization of VM
2017-11-01 15:23:55 DEBUG RunwarLogger agent library failed to init: instrument
agent library failed to init: instrument



INFO: Waiting for server to become available...
INFO: Server engine up and running.
INFO: Configuration processed and server started in 13 seconds.
```

Verify presence of agent:
```
$ docker exec lucee ls -l /root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar
-rw-r--r-- 1 root root 1691 Oct 31 16:15 /root/serverHome/WEB-INF/lucee-server/context/lucee-external-agent.jar
```

**Comment by jamiejackson** [comment]
I'd originally tried this, as you recommended @bdw429s:

```json
"jvm":{
  "args":"-javaagent:\"${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar\""
}
```

But this looks more promising (no quotes around the path).
```json
 "jvm":{
  "args":"-javaagent:${LUCEE_SERVER_CONTEXT}/lucee-external-agent.jar"
}
```

The latter doesn't give errors in the output.

I haven't tried this with my full app yet.

**Comment by jclausen** [comment]
This is a Lucee 5 issue which has been resolved in the current build. Closing.
