### ISSUE TITLE
adobe2023-3.8.0 image throws errors

### ISSUE THREAD

**Issue by bdh8** [Ortus-Solutions/docker-commandbox#75]
after starting up the image and viewing settings in CFAdmin, errors are thrown when showing printer information.  Use of any printer built in function causes errors.  These errors are outside the normal code flow and prevent exception handling... the server simply stops responding in that request, though it does not become unresponsive.

errors dumped to standard out:
```
[INFO] 2023-09-15T16:26:23-06:00 runwar.context - Sep 15, 2023 16:26:23 PM Error [XNIO-1 task-1] - class coldfusion.print.PrintUtil (in unnamed module @0x6d4233cd) cannot access class sun.awt.AppContext (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x6d4233cd The specific sequence of files included or processed is: /usr/local/lib/serverHome/CFIDE/administrator/settings/version.cfm, line: 508
java.lang.IllegalAccessError: class coldfusion.print.PrintUtil (in unnamed module @0x6d4233cd) cannot access class sun.awt.AppContext (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x6d4233cd
 at coldfusion.print.PrintUtil.refreshPrinterList(PrintUtil.java:523)
 at coldfusion.print.PrintBase.getAllPrinters(PrintBase.java:163)
 at coldfusion.print.PrinterInfo.getPrinters(PrinterInfo.java:100)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at coldfusion.runtime.java.JavaProxy.invoke(JavaProxy.java:106)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4142)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4105)
 at cfversion2ecfm1873763958._factor1(/CFIDE/administrator/settings/version.cfm:508)
 at cfversion2ecfm1873763958._factor10(/CFIDE/administrator/settings/version.cfm:500)
 at cfversion2ecfm1873763958.runPage(/CFIDE/administrator/settings/version.cfm:1)
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:257)
 at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:749)
 at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:578)
 at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
 at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:613)
 at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
 at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
 at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
 at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
 at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:97)
 at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
 at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
 at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
 at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
 at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
 at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
 at coldfusion.CfmServlet.service(CfmServlet.java:231)
 at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
 at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
 at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
 at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
 at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
 at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
 at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
 at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
 at runwar.undertow.SSLClientCertHeaderHandler.handleRequest(SSLClientCertHeaderHandler.java:144)
 at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
 at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
 at java.base/java.lang.Thread.run(Thread.java:833)


[ERROR] 2023-09-15T16:26:23-06:00 io.undertow.request - UT005023: Exception handling request to /CFIDE/administrator/settings/version.cfm
javax.servlet.ServletException: ROOT CAUSE:
java.lang.IllegalAccessError: class coldfusion.print.PrintUtil (in unnamed module @0x6d4233cd) cannot access class sun.awt.AppContext (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x6d4233cd
 at coldfusion.print.PrintUtil.refreshPrinterList(PrintUtil.java:523)
 at coldfusion.print.PrintBase.getAllPrinters(PrintBase.java:163)
 at coldfusion.print.PrinterInfo.getPrinters(PrinterInfo.java:100)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at coldfusion.runtime.java.JavaProxy.invoke(JavaProxy.java:106)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4142)
 at coldfusion.runtime.CfJspPage._invoke(CfJspPage.java:4105)
 at cfversion2ecfm1873763958._factor1(/CFIDE/administrator/settings/version.cfm:508)
 at cfversion2ecfm1873763958._factor10(/CFIDE/administrator/settings/version.cfm:500)
 at cfversion2ecfm1873763958.runPage(/CFIDE/administrator/settings/version.cfm:1)
 at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:257)
 at coldfusion.tagext.lang.IncludeTag.handlePageInvoke(IncludeTag.java:749)
 at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:578)
 at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
 at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:613)
 at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
 at coldfusion.filter.PathFilter.invoke(PathFilter.java:162)
 at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
 at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
 at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:97)
 at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
 at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
 at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
 at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
 at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
 at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
 at coldfusion.CfmServlet.service(CfmServlet.java:231)
 at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
 at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
 at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
 at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
 at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
 at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
 at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405)
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
 at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
 at runwar.undertow.SSLClientCertHeaderHandler.handleRequest(SSLClientCertHeaderHandler.java:144)
 at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
 at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
 at java.base/java.lang.Thread.run(Thread.java:833)

 at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:74) ~[?:?]
 at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47) ~[cfmx_bootstrap.jar:development]
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[runwar-4.8.5.jar:4.8.5]
 at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[runwar-4.8.5.jar:4.8.5]
 at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176) ~[runwar-4.8.5.jar:4.8.5]
 at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145) ~[runwar-4.8.5.jar:4.8.5]
 at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92) ~[runwar-4.8.5.jar:4.8.5]
 at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[runwar-4.8.5.jar:4.8.5]
 at runwar.undertow.SSLClientCertHeaderHandler.handleRequest(SSLClientCertHeaderHandler.java:144) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) [runwar-4.8.5.jar:4.8.5]
 at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) [runwar-4.8.5.jar:4.8.5]
 at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [runwar-4.8.5.jar:4.8.5]
 at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) [runwar-4.8.5.jar:4.8.5]
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) [runwar-4.8.5.jar:4.8.5]
 at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449) [runwar-4.8.5.jar:4.8.5]
 at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) [runwar-4.8.5.jar:4.8.5]
 at java.lang.Thread.run(Thread.java:833) [?:?]
```
I have verified that this does not occur on a standard installation of Adobe CF 2023 on windows.

**Comment by bdh8** [comment]
Doing a multi stage build starting with the JRE11 image and then adding Adobe CF 2023 works without these issues, so it appears it is the JRE in the Adobe image that is causing the problems.

```
FROM ortussolutions/commandbox:jre11 as workbench
ENV BOX_SERVER_APP_CFENGINE https://s3.amazonaws.com/downloads.ortussolutions.com/adobe/coldfusion/2023.0.04/cf-engine-2023.0.04.zip
RUN $BUILD_DIR/util/warmup-server.sh

FROM workbench
RUN export CFPM_INSTALL=mail,feed,sqlserver,caching,chart,document,scheduler,ftp,report,pdf,print,image,oracle,zip,debugger \
    && ${BUILD_DIR}/util/warmup-server.sh
```

**Comment by bdw429s** [comment]
This looks like an issue with Running CF on Java 17.  I would ensure you're using an image version that uses at least CommandBox 5.9 and check with Adobe and see what additional opens you may need to add to the JVM.

**Comment by jclausen** [comment]
ACF 2023 is built with Java 17, since that is the recommended JDK for that version.  You would need to add opens for `coldfusion.print` in order to use those Java objects directly.  Your workaround of using JDK11 is also valid.

**Comment by bdh8** [comment]
That was the fix for us… I found 3 add-exports that are used with the Adobe installer, but not in the Ortus adobe images:

--add-exports=java.desktop/sun.awt.image=ALL-UNNAMED 
--add-exports=java.base/sun.util.calendar=ALL-UNNAMED 
--add-exports=java.desktop/sun.awt=ALL-UNNAMED

Is there a reason these are not included in the images?  Is the preferred way to manually add them to the server.jvm.args if required?
